Description of dualfilt1
Home > Wavelet > dualfilt1.m
dualfilt1
PURPOSE
Kingsbury Q-filters for the dual-tree complex DWT
SYNOPSIS
function [af, sf] = dualfilt1
DESCRIPTION
 Kingsbury Q-filters for the dual-tree complex DWT
 USAGE:
    [af, sf] = dualfilt1
 OUTPUT:
    af{i}, i = 1,2 - analysis filters for tree i
    sf{i}, i = 1,2 - synthesis filters for tree i
    note: af{2} is the reverse of af{1}
 REFERENCE:
    N. G. Kingsbury,  "A dual-tree complex wavelet
    transform with improved orthogonality and symmetry
    properties", Proceedings of the IEEE Int. Conf. on
    Image Proc. (ICIP), 2000
 See dualtree
 WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
 http://taco.poly.edu/WaveletSoftware/
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
JJL_cplxdtdwt2D Dual-Tree Complex 2D Discrete Wavelet Transform
JJL_cplxdtdwt3D 3D Complex Dual-Tree Discrete Wavelet Transform
JJL_cplxdual2D_plots cplxdual2D_plots
JJL_cplxdual3D_plots JJL_cplxdual3D_plots
JJL_den2D %
JJL_den3D %
JJL_dtdwt3D Reak 3D Dual-Tree Discrete Wavelet Transform
JJL_dualtree3D_plots dualtree3D_plots
JJL_icplxdtdwt2D Inverse Dual-Tree Complex 2D Discrete Wavelet Transform
JJL_makeDTFilters Function for making JJL version of the dualtree filters. Formats either