Description of farras
Home > Wavelet > farras.m
farras
PURPOSE
Farras nearly symmetric filters for orthogonal
SYNOPSIS
function [af, sf] = farras
DESCRIPTION
 Farras nearly symmetric filters for orthogonal
 2-channel perfect reconstruction filter bank
 USAGE:
    [af, sf] = farras
 OUTPUT:
    af - analysis filters
    sf - synthesis filters
 REFERENCE:
    A. F. Abdelnour and I. W. Selesnick.
    "Nearly symmetric orthogonal wavelet bases",
    Proc. IEEE Int. Conf. Acoust., Speech,
    Signal Processing (ICASSP), May 2001.
 See afb, dwt.
 WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
 http://taco.poly.edu/WaveletSoftware/
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
JJL_dwt2D discrete 2-D wavelet transform
JJL_dwt2D_plots dwt2D_plots
JJL_dwt3D_plots dwt3D_plots
JJL_idwt2D Inverse 2-D Discrete Wavelet Transform