Description of JJL_icplxdtdwt2D
Home > Wavelet > JJL_icplxdtdwt2D.m
JJL_icplxdtdwt2D
PURPOSE
Inverse Dual-Tree Complex 2D Discrete Wavelet Transform
SYNOPSIS
function y = JJL_icplxdtdwt2D(wr1,wi1,wr2,wi2, J, Fsf, sf)
DESCRIPTION
 Inverse Dual-Tree Complex 2D Discrete Wavelet Transform
y = JJL_icplxdtdwt2D(wr1,wi1,wr2,wi2, J, Fsf, sf)
y = JJL_icplxdtdwt2D(wr1,wi1,wr2,wi2, J)
y = JJL_icplxdtdwt2D(w, J, Fsf, sf)
y = JJL_icplxdtdwt2D(w, J)
Adapted From:
 WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
 http://taco.poly.edu/WaveletSoftware/
CROSS-REFERENCE INFORMATION
This function calls:
FSfarras Farras filters organized for the dual-tree
JJL_idwt2D Inverse 2-D Discrete Wavelet Transform
dualfilt1 Kingsbury Q-filters for the dual-tree complex DWT
pm [u v] = pm(a,b);
This function is called by:
JJL_cplxdual2D_plots cplxdual2D_plots
JJL_den2D %