Description of JJL_cplxdtdwt3D
Home > Wavelet > JJL_cplxdtdwt3D.m
JJL_cplxdtdwt3D
PURPOSE
3D Complex Dual-Tree Discrete Wavelet Transform
SYNOPSIS
function w = JJL_cplxdtdwt3D(x, J, Faf, af)
DESCRIPTION
 3D Complex Dual-Tree Discrete Wavelet Transform
Adapted From:
 WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
 http://taco.poly.edu/WaveletSoftware/
CROSS-REFERENCE INFORMATION
This function calls:
FSfarras Farras filters organized for the dual-tree
JJL_dwt3D 3-D Discrete Wavelet Transform
JJL_icplxdtdwt3D Inverse 3D Complex Dual-Tree Discrete Wavelet Transform
dualfilt1 Kingsbury Q-filters for the dual-tree complex DWT
pm4 [u, v, q, r] = pm4(w1, w2, w3, w4);
This function is called by:
JJL_cplxdual3D_plots JJL_cplxdual3D_plots
JJL_den3D %