Description of JJL_idwt2D
Home > Wavelet > JJL_idwt2D.m
JJL_idwt2D
PURPOSE
Inverse 2-D Discrete Wavelet Transform
SYNOPSIS
function y = JJL_idwt2D(w, J, sf)
DESCRIPTION
 Inverse 2-D Discrete Wavelet Transform
 USAGE:
   y = idwt(w, J, sf)
 INPUT:
   w - wavelet coefficients
   J  - number of stages
   sf - synthesis filters
 OUTPUT:
   y - output array
 See dwt2D
Adapted by Jonathan Lareau from:
 WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
 http://taco.poly.edu/WaveletSoftware/
CROSS-REFERENCE INFORMATION
This function calls:
JJL_sfb2D 2D Synthesis Filter Bank
farras Farras nearly symmetric filters for orthogonal
This function is called by:
JJL_dwt2D_plots dwt2D_plots
JJL_icplxdtdwt2D Inverse Dual-Tree Complex 2D Discrete Wavelet Transform
JJL_idtdwt Inverse Dual-Tree Discrete Wavelet Transform
JJL_idtdwt2D Inverse 2-D Dual-Tree Discrete Wavelet Transform