Description of JJL_icplxdtdwt3D
Home > Wavelet > JJL_icplxdtdwt3D.m
JJL_icplxdtdwt3D
PURPOSE
Inverse 3D Complex Dual-Tree Discrete Wavelet Transform
SYNOPSIS
function y = JJL_icplxdtdwt3D(w, J, Fsf, sf)
DESCRIPTION
 Inverse 3D Complex Dual-Tree Discrete Wavelet Transform
 USAGE:
   y = icplxdual3D(w, J, Fsf, sf)
 INPUT:
   J - number of stages
   Fsf - synthesis filter for last stage
   sf - synthesis filters for preceeding stages
 OUTPUT:
   y - output array
 See cplxdual3D
 WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
 http://taco.poly.edu/WaveletSoftware/
CROSS-REFERENCE INFORMATION
This function calls:
JJL_idwt3D Inverse 3-D Discrete Wavelet Transform
pm4inv [u, v, q, r] = pm4(a, b, c, d);
This function is called by:
JJL_cplxdtdwt3D 3D Complex Dual-Tree Discrete Wavelet Transform
JJL_cplxdual3D_plots JJL_cplxdual3D_plots
JJL_den3D %