Description of JJL_idwt3D
Home > Wavelet > JJL_idwt3D.m
JJL_idwt3D
PURPOSE
Inverse 3-D Discrete Wavelet Transform
SYNOPSIS
function y = JJL_idwt3D(w,J,sf)
DESCRIPTION
 Inverse 3-D Discrete Wavelet Transform
 USAGE:
   y = idwt3D(w, J, sf)
 INPUT:
   w - wavelet coefficient
   J  - number of stages
   sf - synthesis filters
 OUTPUT:
   y - output array
 See: dwt3D
Adapted From:
 WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
 http://taco.poly.edu/WaveletSoftware/
CROSS-REFERENCE INFORMATION
This function calls:
JJL_sfb3D 3D Synthesis Filter Bank
This function is called by:
JJL_dwt3D_plots dwt3D_plots
JJL_icplxdtdwt3D Inverse 3D Complex Dual-Tree Discrete Wavelet Transform
JJL_idtdwt3D y = JJL_idtdwt3D(w1,w2,w3,w4,J,Fsf,sf)