Description of JJL_idtdwt3D
Home > Wavelet > JJL_idtdwt3D.m
JJL_idtdwt3D
PURPOSE
y = JJL_idtdwt3D(w1,w2,w3,w4,J,Fsf,sf)
SYNOPSIS
function y = JJL_idtdwt3D(w1,w2,w3,w4,J,Fsf,sf)
DESCRIPTION
y = JJL_idtdwt3D(w1,w2,w3,w4,J,Fsf,sf)
y = JJL_idtdwt3D(w,J,Fsf,sf)
 Inverse 3D Dual-Tree Discrete Wavelet Transform
ADAPTED From:
 WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
 http://taco.poly.edu/WaveletSoftware/
CROSS-REFERENCE INFORMATION
This function calls:
JJL_idwt3D Inverse 3-D Discrete Wavelet Transform
pm4inv [u, v, q, r] = pm4(a, b, c, d);
This function is called by:
JJL_dualtree3D_plots dualtree3D_plots