Description of JJL_makeDTFilters
Home > Wavelet > JJL_makeDTFilters.m
JJL_makeDTFilters
PURPOSE
Function for making JJL version of the dualtree filters. Formats either
SYNOPSIS
function [haf,gaf,hsf,gsf] = JJL_makeDTFilters(J,Faf,af,Fsf,sf,ALTERNATE)
DESCRIPTION
Function for making JJL version of the dualtree filters.  Formats either
the default or user defined filters into JJL_[xxx]dtdwt[N]D() format.
The default filters to use are the Farras designed filters from the POLY
implementation.
USAGE:
   [haf,gaf,hsf,gsf] = JJL_makeDTFilters(J)
   [haf,gaf,hsf,gsf] = JJL_makeDTFilters(J,Faf,af,Fsf,sf)
   [haf,gaf,hsf,gsf] = JJL_makeDTFilters(J,Faf,af,Fsf,sf,ALTERNATE)
INPUTS:
   J - number of scales to use
   Faf - First stage analysis filters
   af - subsequent stage analysis filters
   Fsf - First Stage Synthesis filters
   sf - Subsequent Stage Synthesis filters
   ALTERNATE - [(1),0] Should the subsequent stage filters be alternated
       for stability?
OUTPUTS:
   haf - High Frequency analysis filters
   gaf - Low Frequency analysis filters
   hsf - High Frequency synthisis filters
   hsf - Low Frequency synthisis filters
CROSS-REFERENCE INFORMATION
This function calls:
FSfarras Farras filters organized for the dual-tree
dualfilt1 Kingsbury Q-filters for the dual-tree complex DWT
This function is called by:
JJL_dtdwt 1D Dual-Tree Discrete Wavelet Transform
JJL_dtdwt2D Real 2D Dual-Tree Discrete Wavelet Transform
JJL_idtdwt Inverse Dual-Tree Discrete Wavelet Transform
JJL_idtdwt2D Inverse 2-D Dual-Tree Discrete Wavelet Transform