Description of JJL_dwt2D
Home > Wavelet > JJL_dwt2D.m
JJL_dwt2D
PURPOSE
discrete 2-D wavelet transform
SYNOPSIS
function out = JJL_dwt2D(x, J, af)
DESCRIPTION
 discrete 2-D wavelet transform
 USAGE:
   w = dwt2D(x, stages, af)
 INPUT:
   x - N by M matrix
       1) M, N are both even
       2) min(M,N) >= 2^(J-1)*length(af)
   J - number of stages
   af - analysis filters
 OUPUT:
   w - Matrix of wavelet coefficients
 EXAMPLE:
   [af, sf] = farras;
   x = rand(128,64);
   J = 3;
   w = dwt2D(x,J,af);
   y = idwt2D(w,J,sf);
   err = x - y;
   max(max(abs(err)))
Adapted by Jonathan Lareau from:
 WAVELET SOFTWARE AT POLYTECHNIC UNIVERSITY, BROOKLYN, NY
 http://taco.poly.edu/WaveletSoftware/
CROSS-REFERENCE INFORMATION
This function calls:
JJL_afb2D 2D Analysis Filter Bank
farras Farras nearly symmetric filters for orthogonal
This function is called by:
JJL_cplxdtdwt2D Dual-Tree Complex 2D Discrete Wavelet Transform
JJL_dtdwt2D Real 2D Dual-Tree Discrete Wavelet Transform
JJL_dwt2D_plots dwt2D_plots